name: Deploy Power Platform Solution new
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Power Platform tools
      uses: microsoft/powerplatform-actions/actions-install@v1
    
    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: "https://org9df2a3ac.crm.dynamics.com"
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ secrets.TENANT_ID }}
        solution-name: "sol1"
        solution-output-file: Games/sol1.zip
      #  solution-name: "sol1"
      #  solution-output-file: "exported-solution.zip"
       # managed: false
    
    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: Games/sol1.zip
        solution-folder: Games/sol1
        solution-type: 'Unmanaged'
        overwrite-files: true
    
    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-folder: Games/sol1
        solution-file: Games/sol1.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: "https://org4174b73a.crm.dynamics.com"
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ secrets.TENANT_ID }}
        solution-file: Games/sol1.zip
        force-overwrite: true
        publish-changes: true

    
