name: Deploy Power Platform Solution Self-hosted
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Power Platform tools
      uses: microsoft/powerplatform-actions/actions-install@v1
      with:
        add-tools-to-path: true  # This is the key parameter to add

    - name: Install Power Platform CLI
      shell: pwsh
      run: |
        # Create directory for solutions
        New-Item -ItemType Directory -Force -Path "exportedSolutions"

         # Set PAC CLI path directly
        $cliPath = "C:\Users\saikiran.s\AppData\Local\Microsoft\PowerAppsCLI"
        $env:PATH += ";$cliPath"
        
        Write-Host "Using PAC CLI from: $cliPath"
        echo "PAC_CLI_PATH=$cliPath" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Authenticate and Export Solution
      shell: pwsh
      run: |
          # Set the PAC CLI path
          $env:PATH += ";$env:PAC_CLI_PATH"
    
          # Confirm PAC CLI is available
          Write-Host "Using PAC CLI from: $env:PAC_CLI_PATH"
          Get-ChildItem "$env:PAC_CLI_PATH" | Select-Object Name
    
          # Authenticate with source environment
          & "$env:PAC_CLI_PATH\pac.cmd" auth create --applicationId "${{ secrets.CLIENT_ID }}" --tenant "${{ secrets.TENANT_ID }}" --clientSecret "${{ secrets.CLIENT_SECRET }}" --url "https://org9df2a3ac.crm.dynamics.com"
          
          # Export solution
          & "$env:PAC_CLI_PATH\pac.cmd" solution export --name "sol1" --path "./exportedSolutions/sol1.zip" --managed false

          # Run solution checker
          & "$env:PAC_CLI_PATH\pac.cmd" solution check --path "./exportedSolutions/sol1.zip" --outputDirectory "./exportedSolutions/solutionCheckerOutput"

          # Optional: list the contents of the output directory
          Get-ChildItem "./exportedSolutions/solutionCheckerOutput"

          
          # Authenticate with target environment
          & "$env:PAC_CLI_PATH\pac.cmd" auth create --applicationId "${{ secrets.CLIENT_ID }}" --tenant "${{ secrets.TENANT_ID }}" --clientSecret "${{ secrets.CLIENT_SECRET }}" --url "https://org4174b73a.crm.dynamics.com"
          
          # Import solution
          & "$env:PAC_CLI_PATH\pac.cmd" solution import --path "./exportedSolutions/sol1.zip" --async false


    - name: Extract SARIF file from Solution Checker results
      run: |
        $zipPath = "exportedSolutions/solutionCheckerOutput/*.zip"
        $outputDir = "checker-results"
        mkdir $outputDir
        Expand-Archive -Path $zipPath -DestinationPath $outputDir -Force
        $sarif = Get-ChildItem $outputDir -Recurse -Filter *.sarif | Select-Object -First 1
        if ($sarif) {
          Copy-Item $sarif.FullName -Destination "solution-check-results.sarif"
        } else {
          Write-Error "No SARIF file found in extracted report."
        }
      shell: pwsh

    - name: Upload SARIF to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: solution-check-results.sarif

    
