name: Deploy Power Platform Solution1
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Install Power Platform CLI
      shell: pwsh
      run: |
        # Create directory for solutions
        New-Item -ItemType Directory -Force -Path "exportedSolutions"
        
        # Download and install the Power Platform CLI
        Invoke-WebRequest -Uri https://aka.ms/PowerAppsCLI -OutFile PowerAppsCLI.msi
        Start-Process msiexec.exe -ArgumentList '/i PowerAppsCLI.msi /quiet /norestart' -Wait
        
        # Refresh PowerShell session's PATH environment variable
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        
        # Try to find directly in Program Files (more reliable than recursive search)
        $cliPath = "C:\Program Files (x86)\Microsoft\Power Platform CLI\"
        if (Test-Path "$cliPath\pac.exe") {
            $env:PATH += ";$cliPath"
            Write-Host "Found PAC at: $cliPath\pac.exe"
            echo "PAC_CLI_PATH=$cliPath" | Out-File -FilePath $env:GITHUB_ENV -Append
        } else {
            Write-Host "PAC not found at default location, checking alternative locations..."
            foreach ($drive in @("C:", "D:")) {
                foreach ($programFiles in @("\Program Files", "\Program Files (x86)")) {
                    $potentialPath = Join-Path -Path "$drive$programFiles" -ChildPath "Microsoft\Power Platform CLI\pac.exe"
                    if (Test-Path $potentialPath) {
                        $cliPath = Split-Path -Parent $potentialPath
                        $env:PATH += ";$cliPath"
                        Write-Host "Found PAC at: $potentialPath"
                        echo "PAC_CLI_PATH=$cliPath" | Out-File -FilePath $env:GITHUB_ENV -Append
                        break
                    }
                }
            }
        }
        
        # Try another common location - sometimes it's here
        if (-not (Test-Path "$env:PAC_CLI_PATH\pac.exe")) {
            $otherPath = "C:\Users\runneradmin\AppData\Local\Microsoft\PowerAppsCLI"
            if (Test-Path "$otherPath\pac.exe") {
                $env:PATH += ";$otherPath"
                Write-Host "Found PAC at: $otherPath\pac.exe"
                echo "PAC_CLI_PATH=$otherPath" | Out-File -FilePath $env:GITHUB_ENV -Append
            }
        }
        
        # Install pacTelemetryUpload (sometimes needed)
        # This adds Microsoft.PowerApps.CLI.Tool to your path
        dotnet tool install -g Microsoft.PowerApps.CLI.Tool
        
        # Try to verify installation
        Get-Command -Name pac -ErrorAction SilentlyContinue | Out-Host
        if (-not $?) {
            Write-Host "Cannot find pac command in PATH, will try to use full path"
        }
        
    - name: Authenticate and Export Solution
      shell: pwsh
      run: |
        Write-Host "PATH: $env:PATH"
        Write-Host "PAC CLI Path: $env:PAC_CLI_PATH"
        
        # Try to find pac
        $pacCommand = "pac"
        if (Test-Path "$env:PAC_CLI_PATH\pac.exe") {
            $pacCommand = "$env:PAC_CLI_PATH\pac.exe"
        } elseif (Test-Path "C:\Program Files (x86)\Microsoft\Power Platform CLI\pac.exe") {
            $pacCommand = "C:\Program Files (x86)\Microsoft\Power Platform CLI\pac.exe"
        } else {
            Get-ChildItem -Path "C:\Program Files" -Filter "pac.exe" -Recurse -Depth 3 -ErrorAction SilentlyContinue | ForEach-Object {
                $pacCommand = $_.FullName
                Write-Host "Found pac.exe at: $pacCommand"
            }
        }
        
        Write-Host "Using pac command: $pacCommand"
        
        # Authenticate with source environment
        & $pacCommand auth create --applicationId "${{ secrets.CLIENT_ID }}" --tenant "${{ secrets.TENANT_ID }}" --clientSecret "${{ secrets.CLIENT_SECRET }}" --url "https://org9df2a3ac.crm.dynamics.com"
        
        # Export solution
        & $pacCommand solution export --name "sol1" --path "./exportedSolutions" --managed false
        
        # Authenticate with target environment
        & $pacCommand auth create --applicationId "${{ secrets.CLIENT_ID }}" --tenant "${{ secrets.TENANT_ID }}" --clientSecret "${{ secrets.CLIENT_SECRET }}" --url "https://org4174b73a.crm.dynamics.com"
        
        # Import solution
        & $pacCommand solution import --path "./exportedSolutions/sol1_1_0_0_*.zip" --async false
