name: Deploy Power Platform Solution1
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Install Power Platform CLI
      shell: pwsh
      run: |
        # Create directory for solutions
        New-Item -ItemType Directory -Force -Path "exportedSolutions"
        
        # Download and install the Power Platform CLI
        Invoke-WebRequest -Uri https://aka.ms/PowerAppsCLI -OutFile PowerAppsCLI.msi
        Start-Process msiexec.exe -ArgumentList '/i PowerAppsCLI.msi /quiet /norestart' -Wait
        
        # Set PAC CLI path directly
        $cliPath = "C:\Users\runneradmin\AppData\Local\Microsoft\PowerAppsCLI"
        $env:PATH += ";$cliPath"
        
        Write-Host "Using PAC CLI from: $cliPath"
        echo "PAC_CLI_PATH=$cliPath" | Out-File -FilePath $env:GITHUB_ENV -Append
    
        # Install pacTelemetryUpload (sometimes needed)
        dotnet tool install -g Microsoft.PowerApps.CLI.Tool
        
        # Verify installation
        Get-Command -Name pac -ErrorAction SilentlyContinue | Out-Host
        if (-not $?) {
            Write-Host "Cannot find pac command in PATH, check installation."
        }

        
    - name: Authenticate and Export Solution
      run: |
          # Set the PAC CLI path
          $env:PAC_CLI_PATH = "C:\Users\runneradmin\AppData\Local\Microsoft\PowerAppsCLI"
          $env:PATH += ";$env:PAC_CLI_PATH"
    
          # Confirm PAC CLI is available
          Write-Host "Using PAC CLI from: $env:PAC_CLI_PATH"
    
          # Authenticate with source environment
          & "$env:PAC_CLI_PATH\pac.cmd" auth create --applicationId "${{ secrets.CLIENT_ID }}" --tenant "${{ secrets.TENANT_ID }}" --clientSecret "${{ secrets.CLIENT_SECRET }}" --url "https://org9df2a3ac.crm.dynamics.com"
          
          # Export solution
          & "$env:PAC_CLI_PATH\pac.cmd" solution export --name "sol1" --path "./exportedSolutions" --managed false

          # Authenticate with target environment
          & "$env:PAC_CLI_PATH\pac.cmd" auth create --applicationId "${{ secrets.CLIENT_ID }}" --tenant "${{ secrets.TENANT_ID }}" --clientSecret "${{ secrets.CLIENT_SECRET }}" --url "https://org4174b73a.crm.dynamics.com"
          
          # Export solution
          & "$env:PAC_CLI_PATH\pac.cmd" solution import --path "./exportedSolutions/sol1.zip" --async false

