name: Deploy Power Platform Solution1
on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch

jobs:
  deploy:
    runs-on: windows-latest  

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Authenticate with Power Platform
      shell: pwsh
      run: |
        pac auth create --applicationId "${{ secrets.CLIENT_ID }}" `
                        --tenant "${{ secrets.TENANT_ID }}" `
                        --clientSecret "${{ secrets.CLIENT_SECRET }}" `
                        --url "https://org9df2a3ac.crm.dynamics.com"
    
                        
    - name: Export Solution from Source Environment
      shell: pwsh
      run: |
        pac solution export --name "sol1" `
                    --path "./exportedSolutions" `
                    --managed false
                            
    - name: Authenticate with Power Platform
      shell: pwsh
      run: |
        pac auth create --applicationId "${{ secrets.CLIENT_ID }}" `
                        --tenant "${{ secrets.TENANT_ID }}" `
                        --clientSecret "${{ secrets.CLIENT_SECRET }}" `
                        --url "https://org4174b73a.crm.dynamics.com"

                            

    - name: Deploy Solution to Target Environment
      shell: pwsh
      run: |
        pac solution import --path "./exportedSolutions/sol1_unmanaged.zip" `
                            --async false
                            
   
