name: Deploy Power Platform Solution1
on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch
jobs:
  deploy:
    runs-on: windows-latest  
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Install Power Platform CLI
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://aka.ms/PowerAppsCLI -OutFile PowerAppsCLI.msi
        Start-Process msiexec.exe -ArgumentList '/i PowerAppsCLI.msi /quiet /norestart' -Wait
        
        # Find where pac.exe is installed
        $pacPath = Get-ChildItem -Path "C:\" -Filter "pac.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
        Write-Host "PAC executable found at: $pacPath"
        
        # Get the directory and add to PATH
        $pacDir = Split-Path -Parent $pacPath
        $env:PATH += ";$pacDir"
        Write-Host "Updated PATH: $env:PATH"
        
        # Create a step output variable for use in later steps
        echo "PAC_DIR=$pacDir" >> $env:GITHUB_ENV
        
        # Test pac command using full path
        & $pacPath
        echo "Installed PAC CLI"
        
    - name: Authenticate with Power Platform (Source)
      shell: pwsh
      run: |
        # Use full path to pac
        & "$env:PAC_DIR\pac" auth create --applicationId "${{ secrets.CLIENT_ID }}" `
                        --tenant "${{ secrets.TENANT_ID }}" `
                        --clientSecret "${{ secrets.CLIENT_SECRET }}" `
                        --url "https://org9df2a3ac.crm.dynamics.com"
    
    - name: Export Solution from Source Environment
      shell: pwsh
      run: |
        & "$env:PAC_DIR\pac" solution export --name "sol1" `
                    --path "./exportedSolutions" `
                    --managed false
                            
    - name: Authenticate with Power Platform (Target)
      shell: pwsh
      run: |
        & "$env:PAC_DIR\pac" auth create --applicationId "${{ secrets.CLIENT_ID }}" `
                        --tenant "${{ secrets.TENANT_ID }}" `
                        --clientSecret "${{ secrets.CLIENT_SECRET }}" `
                        --url "https://org4174b73a.crm.dynamics.com"
                            
    - name: Deploy Solution to Target Environment
      shell: pwsh
      run: |
        & "$env:PAC_DIR\pac" solution import --path "./exportedSolutions/sol1_unmanaged.zip" `
                            --async false
